# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debugg
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debugg)
  GLFW_config = debugg
  AnvilEngine_config = debugg
  Forge_config = debugg

else ifeq ($(config),debug)
  GLFW_config = debug
  AnvilEngine_config = debug
  Forge_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  AnvilEngine_config = release
  Forge_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW AnvilEngine Forge

.PHONY: all clean help $(PROJECTS) Dependencies Editor Engine

all: $(PROJECTS)

Dependencies: GLFW

Editor: Forge

Engine: AnvilEngine

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C AnvilEngine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

AnvilEngine: GLFW
ifneq (,$(AnvilEngine_config))
	@echo "==== Building AnvilEngine ($(AnvilEngine_config)) ===="
	@${MAKE} --no-print-directory -C AnvilEngine -f Makefile config=$(AnvilEngine_config)
endif

Forge: AnvilEngine GLFW
ifneq (,$(Forge_config))
	@echo "==== Building Forge ($(Forge_config)) ===="
	@${MAKE} --no-print-directory -C Forge -f Makefile config=$(Forge_config)
endif

clean:
	@${MAKE} --no-print-directory -C AnvilEngine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C AnvilEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Forge -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debugg"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   AnvilEngine"
	@echo "   Forge"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"