#pragma once

// default banner pasted at the beginning of a log file
#define ANV_STD_LOG_BANNER \
"=================================================================\n" \
"== THIS FILE AND ITS CONTENTS WERE GENERATED BY THE ANVLOG LIB ==\n" \
"=================================================================\n"